ci:
  autofix: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
        exclude: \.clang-format$
      - id: check-json
      - id: check-xml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-merge-conflict

  ######################################################################
  # Python Formatting
  ######################################################################

  # Use Ruff to handle formatting, import sorting, and linting all at once.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.10
    hooks:
      # Code formatting (replaces black and isort)
      - id: ruff-format
      # Linting and auto-fixing (replaces flake8)
      - id: ruff
        args: [--fix]

  # # For Python import sorting
  # - repo: https://github.com/pycqa/isort
  #   rev: "5.12.0"
  #   hooks:
  #     - id: isort

  # # Yet Another Python Formatter
  # # NOTE(hlim): Python 3.12 (Ubuntu 24.04) is now not supported by yapf
  # # - repo: https://github.com/pre-commit/mirrors-yapf
  # #   rev: v0.32.0
  # #   hooks:
  # #     - id: yapf
  # #       additional_dependencies: [toml]

  # - repo: https://github.com/psf/black
  #   rev: 23.12.1
  #   hooks:
  #     - id: black

  # - repo: https://github.com/PyCQA/flake8
  #   rev: 5.0.4
  #   hooks:
  #     - id: flake8
  #       exclude: 'python/utils/download_datasets'
  #       # To avoid conflict between flake and black
  #       args: ["--ignore=E501"]

  ######################################################################
  # Markdown Formatting
  ######################################################################
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.9
    hooks:
      - id: mdformat
        exclude: 'github/'
